### ISSUE TITLE
Doesn’t work with Starfield Script Extender (SFSE)

### ISSUE THREAD

**Issue by chicouskiluiz** [Tautellini/Starfield-WeaponFoV-CheatEngine#2]
I tested the table with the game without mods and it worked very well. However, when adding the [SFSE ](https://www.nexusmods.com/starfield/mods/106) this address is no longer found. Do you plan to add support for this in the future?
If not, could you give me some hints on how you found that address? I would like to make a new specific table for SFSE.

**Comment by Survivalistic** [comment]
> I tested the table with the game without mods and it worked very well. However, when adding the [SFSE ](https://www.nexusmods.com/starfield/mods/106) this address is no longer found. Do you plan to add support for this in the future? If not, could you give me some hints on how you found that address? I would like to make a new specific table for SFSE.

I am using it with SFSE and it works fine, make sure you're selecting the starfield.exe and not the sfse_loader.exe

**Comment by Tautellini** [comment]
What Survivalistic said is correct. Make sure to select the starfield exe itself when loading up the Table. Please let me know if this helped, because the last time I tested it, it was working perfectly fine and im also using the SFSE already.

Btw, anyway, unless you dont already use a Plugin, there is no reason to use the SFSE at the moment, because it does nothing besides functioning as a plugin loader/dll injector at the moment. There is no benefit in installing it. Just for your interest.

However, im **preparing the fix as a SFSE plugin** at the moment. Need some more days, because the SFSE project is still very early and I already had some hard time getting a template plugin to run. But this will be a more permanent fix that doesn't require cheat engine anymore.

**Comment by chicouskiluiz** [comment]
Thanks for the feedback! My mistake lol I found the problem here, I was loading the correct application, the problem was that I had renamed the Starfield and SFSE executables to be able to launch it directly through Steam. I just needed to rename the executable inside the table from `Starfield.exe+79FD448` to `starfieldgame.exe+79FD448`. Thank you again 😁.
